"""Add price_average and period fields

Revision ID: a69c589db1e4
Revises: ace44cc544c0
Create Date: 2025-12-28 17:40:50.455747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69c589db1e4'
down_revision: Union[str, None] = 'ace44cc544c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('is_regional_average', sa.Boolean(), nullable=True))
    op.add_column('price_entries', sa.Column('price_average', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price_entries', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('price_entries', sa.Column('period_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_entries', 'period_end')
    op.drop_column('price_entries', 'period_start')
    op.drop_column('price_entries', 'price_average')
    op.drop_column('markets', 'is_regional_average')
    # ### end Alembic commands ###
