"""Initial migration

Revision ID: ace44cc544c0
Revises: 
Create Date: 2025-12-28 16:46:27.452496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace44cc544c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_category'), 'commodities', ['category'], unique=False)
    op.create_index(op.f('ix_commodities_name'), 'commodities', ['name'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_name'), 'markets', ['name'], unique=False)
    op.create_index(op.f('ix_markets_region'), 'markets', ['region'], unique=False)
    op.create_table('price_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_prevailing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_entries_report_date'), 'price_entries', ['report_date'], unique=False)
    op.create_index(op.f('ix_price_entries_report_type'), 'price_entries', ['report_type'], unique=False)
    op.create_table('supply_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('volume_metric_tons', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_indices_date'), 'supply_indices', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_indices_date'), table_name='supply_indices')
    op.drop_table('supply_indices')
    op.drop_index(op.f('ix_price_entries_report_type'), table_name='price_entries')
    op.drop_index(op.f('ix_price_entries_report_date'), table_name='price_entries')
    op.drop_table('price_entries')
    op.drop_index(op.f('ix_markets_region'), table_name='markets')
    op.drop_index(op.f('ix_markets_name'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_commodities_name'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_category'), table_name='commodities')
    op.drop_table('commodities')
    # ### end Alembic commands ###
